os: osx
sudo: required
language: generic

install:
    - "./build.sh"

deploy:
  provider: releases
  api_key:
    secure: hF3C7uG83N57UPRxCFKcgkAVDEODvpVTafIdJrjVO9kNXZoFaoRcBApWBC+tZwZAnFOil3XZMciFVVDcvxq8rIX1p41lfVDWfV0L711hIoI1xV+JyKLE44JYlKnVhP9Y+9OvkmDjPgavuqfi/Bujh9aE8BpxkSvrLLDg3ucAbUeFlapfbAOTf+vds5cLxMySJns8zfAFcboGv6+HYCvnXrCPlcdo3v26Hd5DVM80+LgjfGrMnFMtiLNbqJw2r9u887icGGU0UZfOA94RqUV6i081LSuvlEnF2kJo0oGmO54VQMB2y4WrfBOW1ubXxvLLRgnDuV72yIxQmSq89nz3f/WvNSO0pm5UAv+LL3xSOR7MPW+NE3gCC6rbCUJJR/R5+3uxi1y4mcfNpZhHsH0o2aR21vi1E5mcqkS40qoheHO18L2Ppo2FkEDucm1JwjDacMlyiJdtoSJiJZS25q4iGTINhbxTeI19dm0bIKtJ67qAoy+PFI3QX1ENK+eT/+1mShK4SUyAkdXzPCcU38QM0Ywctq+b5eAB6CnipT3n3UcTWOWp50bhdyzKV4TK7GfmpTHw8TKTDbe6qWgHGUV09a6SnQCuikkFIrbJkKDKw4gBdiOxQamYDNNSbfnWbGitY3106dIbrye8XNyIZzLC9qZvVwra785aesDNA4VnVvA=
  file: PythonDotApp.dmg
  skip_cleanup: true
  on:
    tags: true
